/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petscare;

import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter; 
import net.proteanit.sql.DbUtils;
import static petscare.Admin.currentAdminID;

/**
 *
 * @author Maryam Tariq
 */
public class ManageFood extends javax.swing.JFrame {
    
    Connection con;
    Statement st;
    ResultSet rs;
    String selectedImagePath;

    /**
     * Creates new form ManageFood
     */
    public ManageFood() {
        initComponents();
        fillTable();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        addWindowListener(
            new WindowAdapter()
            {
                @Override
                public void windowClosed(WindowEvent event)
                {
                    closeDB();
                    System.exit(0);
                }
            }
        );
    }
    
    public void fillTable()
    {
        try
        {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/PetsCare","root","root");
            st=con.createStatement();
            rs=st.executeQuery("SELECT FoodID ,Food_Name, VendorName, Price, Food_Type, Quantity, AdminID FROM Food");
            
            foodTable.setModel(DbUtils.resultSetToTableModel(rs));
            admIDTxt.setText(String.valueOf(currentAdminID));
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(ManageFood.this, ex);
        }
    }
    
    public void closeDB()
    {
        try
        {
            rs.close();
            st.close();
            con.close();
        }
        
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(ManageFood.this, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        foodIDTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        venNameTxt = new javax.swing.JTextField();
        typeTxt = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        foodTable = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        quantTxt = new javax.swing.JTextField();
        priceTxt = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        admIDTxt = new javax.swing.JTextField();
        imageButton = new javax.swing.JButton();
        imageLable = new javax.swing.JLabel();
        imageLable2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Food");
        setMaximumSize(new java.awt.Dimension(900, 550));
        setMinimumSize(new java.awt.Dimension(900, 550));
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(78, 95, 200));
        jLabel20.setText("Manage Food");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(143, 144, 150));
        jLabel21.setText("Name");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(143, 144, 150));
        jLabel22.setText("Food ID");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(143, 144, 150));
        jLabel23.setText("Vendor Name");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(143, 144, 150));
        jLabel24.setText("Price");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(143, 144, 150));
        jLabel25.setText("Quantity");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(143, 144, 150));
        jLabel26.setText("Type");

        foodIDTxt.setEditable(false);
        foodIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodIDTxtActionPerformed(evt);
            }
        });

        venNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venNameTxtActionPerformed(evt);
            }
        });

        foodTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Food_ID", "Name", "VendorName", "Price", "Type", "Quantity"
            }
        ));
        foodTable.setRowHeight(20);
        foodTable.setSelectionBackground(new java.awt.Color(204, 204, 255));
        foodTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(foodTable);

        addButton.setBackground(new java.awt.Color(78, 95, 200));
        addButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setBackground(new java.awt.Color(78, 95, 200));
        removeButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        removeButton.setForeground(new java.awt.Color(255, 255, 255));
        removeButton.setText("REMOVE");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(78, 95, 200));
        editButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setText("EDIT");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(78, 95, 200));
        clearButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 27)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(193, 193, 255));
        jLabel27.setText("FOOD LIST");

        backLabel.setForeground(new java.awt.Color(144, 143, 150));
        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petscare/Icon/back (1) (1) (1) (1).png"))); // NOI18N
        backLabel.setText(" BACK");
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(144, 143, 150));
        jLabel16.setText("Admin ID");

        admIDTxt.setEditable(false);
        admIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admIDTxtActionPerformed(evt);
            }
        });

        imageButton.setBackground(new java.awt.Color(78, 95, 200));
        imageButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        imageButton.setForeground(new java.awt.Color(255, 255, 255));
        imageButton.setText("Browse Image");
        imageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageButtonActionPerformed(evt);
            }
        });

        imageLable.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        imageLable.setForeground(new java.awt.Color(144, 143, 150));
        imageLable.setText("Image");

        imageLable2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        imageLable2.setForeground(new java.awt.Color(144, 143, 150));
        imageLable2.setText(" No Image Chose");
        imageLable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(imageLable))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(foodIDTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(nameTxt)
                            .addComponent(venNameTxt)
                            .addComponent(imageButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel24))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(priceTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(quantTxt)
                                    .addComponent(typeTxt)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(admIDTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
                        .addGap(146, 146, 146))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeButton)
                        .addGap(45, 45, 45)
                        .addComponent(clearButton)
                        .addGap(94, 94, 94))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(343, 343, 343))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(backLabel)
                        .addGap(281, 281, 281)
                        .addComponent(jLabel20))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(imageLable2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backLabel)
                    .addComponent(jLabel20))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(foodIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(venNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(typeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(quantTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(admIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(imageButton)
                        .addComponent(imageLable)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imageLable2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(removeButton)
                    .addComponent(clearButton)
                    .addComponent(editButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(914, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void foodIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodIDTxtActionPerformed

    private void venNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_venNameTxtActionPerformed

    private void foodTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodTableMouseClicked
        // TODO add your handling code here:

        try
        {
            int selectRow = foodTable.getSelectedRow();
            int SelectID = Integer.parseInt(foodTable.getModel().getValueAt(selectRow,0).toString());

            String query = "SELECT * FROM Food WHERE FoodID = " + SelectID;
            rs = st.executeQuery(query);

            rs.next();
            foodIDTxt.setText(String.format("%d", rs.getInt("FoodID")));
            nameTxt.setText(rs.getString("Food_Name"));
            venNameTxt.setText(rs.getString("VendorName"));
            priceTxt.setText(String.format("%.2f", rs.getDouble("Price")));
            typeTxt.setText(rs.getString("Food_Type"));
            quantTxt.setText(String.format("%d", rs.getInt("Quantity")));
            admIDTxt.setText(String.format("%d", currentAdminID));
            
            String path = rs.getString("ImagePath");
            ImageIcon image = new ImageIcon(getClass().getResource("Icon/" + path));
            Image img = image.getImage();
            Image imgImage = img.getScaledInstance(imageLable2.getWidth(),imageLable2.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(imgImage);
            imageLable2.setIcon(scaledIcon);
            imageLable2.setText(rs.getString("ImagePath"));

        }

        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(ManageFood.this, ex);
        }
    }//GEN-LAST:event_foodTableMouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        
        if(nameTxt.getText().isEmpty() || venNameTxt.getText().isEmpty() || priceTxt.getText().isEmpty() || typeTxt.getText().isEmpty() || quantTxt.getText().isEmpty() || imageLable2.getIcon() == null)
            JOptionPane.showMessageDialog(this, "Missing Information", "Error", JOptionPane.WARNING_MESSAGE);
        else
        {
            try
            {
                if(Integer.parseInt(quantTxt.getText()) <= 0 || Integer.parseInt(priceTxt.getText()) <= 0)
                {
                    JOptionPane.showMessageDialog(this, "Enter Positive Value", "Quantity or Price Error", JOptionPane.WARNING_MESSAGE);
                }
                else
                {
                    PreparedStatement insertQuery = con.prepareStatement("INSERT INTO Food (Food_Name, VendorName, Price, Food_Type, Quantity, ImagePath ,AdminID)\n" +
                        "VALUES (?, ?, ?, ?, ?, ?, ?)");

                    insertQuery.setString(1, nameTxt.getText());
                    insertQuery.setString(2, venNameTxt.getText());
                    insertQuery.setDouble(3, Double.valueOf(priceTxt.getText()));
                    insertQuery.setString(4, typeTxt.getText());
                    insertQuery.setInt(5, Integer.valueOf(quantTxt.getText()));
                    insertQuery.setString(6, imageLable2.getText());
                    insertQuery.setInt(7, Integer.valueOf(admIDTxt.getText()));

                    int result = insertQuery.executeUpdate();
                    if(result == 1)
                    JOptionPane.showMessageDialog(ManageFood.this, "Food: " + nameTxt.getText()  + " is Addedd");

                    closeDB();
                    fillTable();
                }
            }

            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
            }
            
            catch (NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(this, "You Enter Wrong Entery Type", "Error", JOptionPane.WARNING_MESSAGE);
            }

            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(ManageFood.this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:

        try
        {
            int confirm = JOptionPane.showConfirmDialog(ManageFood.this, "You Want to Delete Selected Recored?", "Delete Recored", JOptionPane.YES_NO_OPTION);
            if(confirm == JOptionPane.YES_OPTION)
            {
                String DeleteQuery = "DELETE FROM Food WHERE FoodID = " + foodIDTxt.getText();
                int result = st.executeUpdate(DeleteQuery);
                if(result == 1)
                JOptionPane.showMessageDialog(ManageFood.this, "Selected Recored is Deleted");

                foodIDTxt.setText("");
                nameTxt.setText("");
                venNameTxt.setText("");
                priceTxt.setText("");
                typeTxt.setText("");
                quantTxt.setText("");
                imageLable2.setIcon(null);
                imageLable2.setText(" No Image Chose");
                admIDTxt.setText(String.valueOf(currentAdminID));

                closeDB();
                fillTable();
            }
        }

        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(ManageFood.this, ex.getMessage());
        }

        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(ManageFood.this, ex.getMessage());
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        if(nameTxt.getText().isEmpty() || venNameTxt.getText().isEmpty() || priceTxt.getText().isEmpty() || typeTxt.getText().isEmpty() || quantTxt.getText().isEmpty() || admIDTxt.getText().isEmpty() || imageLable2.getIcon() == null)
            JOptionPane.showMessageDialog(this, "Missing Information", "Error", JOptionPane.WARNING_MESSAGE);
        else
        {
            try
            {
                if(Integer.parseInt(quantTxt.getText()) <= 0 || Integer.parseInt(priceTxt.getText()) <= 0)
                {
                    JOptionPane.showMessageDialog(this, "Enter Positive Value", "Quantity or Price Error", JOptionPane.WARNING_MESSAGE);
                }
                else
                {
                    PreparedStatement updateQuery = con.prepareStatement("UPDATE Food SET Food_Name = ?, VendorName = ?, Price = ?, Food_Type = ?, Quantity = ?, ImagePath = ?, AdminID = ? WHERE FoodID = ?");

                    updateQuery.setString(1, nameTxt.getText());
                    updateQuery.setString(2, venNameTxt.getText());
                    updateQuery.setDouble(3, Double.valueOf(priceTxt.getText()));
                    updateQuery.setString(4, typeTxt.getText());
                    updateQuery.setInt(5, Integer.valueOf(quantTxt.getText()));
                    updateQuery.setString(6, imageLable2.getText());
                    updateQuery.setInt(7, Integer.valueOf(admIDTxt.getText()));
                    updateQuery.setInt(8, Integer.valueOf(foodIDTxt.getText()));

                    int result = updateQuery.executeUpdate();
                    if(result == 1)
                    JOptionPane.showMessageDialog(ManageFood.this, "Selected Recored is Updated");
                    else
                    JOptionPane.showMessageDialog(ManageFood.this, "Failed: Selected Recored is not Updated");

                    closeDB();
                    fillTable();
                }
            }

            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(ManageFood.this, ex.getMessage());
            }

            catch (NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(this, "You Enter Wrong Entery Type", "Error", JOptionPane.WARNING_MESSAGE);
            }

            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(ManageFood.this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:

        foodIDTxt.setText("");
        nameTxt.setText("");
        venNameTxt.setText("");
        priceTxt.setText("");
        typeTxt.setText("");
        quantTxt.setText("");
        imageLable2.setIcon(null);
        imageLable2.setText(" No Image Chose");
        admIDTxt.setText(String.valueOf(currentAdminID));
    }//GEN-LAST:event_clearButtonActionPerformed

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // TODO add your handling code here:

        this.setVisible(false);
        Admin admin = new Admin();
        admin.setVisible(true);
    }//GEN-LAST:event_backLabelMouseClicked

    private void admIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admIDTxtActionPerformed

    private void imageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser imageChooser = new JFileChooser("C:\\Users\\Mzts5\\Downloads\\PetsCare\\src\\petscare\\Icon");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image files (*.PNG,*.JPG, *.JPEG)", "PNG","JPG", "JPEG");
        imageChooser.setFileFilter(filter);

        int result = imageChooser.showOpenDialog(this);

        if(result == JFileChooser.APPROVE_OPTION)
        {
            File imageFile = imageChooser.getSelectedFile();
            selectedImagePath = imageFile.getName();

            ImageIcon image = new ImageIcon(getClass().getResource("Icon/" + selectedImagePath));
            Image img = image.getImage();
            Image imgImage = img.getScaledInstance(imageLable2.getWidth(),imageLable2.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(imgImage);
            imageLable2.setIcon(scaledIcon);
            imageLable2.setText(selectedImagePath);
        }
    }//GEN-LAST:event_imageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageFood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField admIDTxt;
    private javax.swing.JLabel backLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField foodIDTxt;
    private javax.swing.JTable foodTable;
    private javax.swing.JButton imageButton;
    private javax.swing.JLabel imageLable;
    private javax.swing.JLabel imageLable2;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JTextField quantTxt;
    private javax.swing.JButton removeButton;
    private javax.swing.JTextField typeTxt;
    private javax.swing.JTextField venNameTxt;
    // End of variables declaration//GEN-END:variables
}
