/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petscare;

import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter; 
import net.proteanit.sql.DbUtils;
import static petscare.Admin.currentAdminID;

/**
 *
 * @author Maryam Tariq
 */
public class ManagePet extends javax.swing.JFrame {
    
    Connection con;
    Statement st;
    ResultSet rs;
    String selectedImagePath;

    /**
     * Creates new form ManagePet
     */
    public ManagePet() {
        initComponents();
        fillTable();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        addWindowListener(
            new WindowAdapter()
            {
                @Override
                public void windowClosed(WindowEvent event)
                {
                    closeDB();
                    System.exit(0);
                }
            }
        );
    }
    
    public void fillTable()
    {
        try
        {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/PetsCare","root","root");
            st=con.createStatement();
            rs=st.executeQuery("SELECT PetID, Pet_Name, Age, Species, Price, Pet_Type, AdminID FROM Pet");
            
            petTable.setModel(DbUtils.resultSetToTableModel(rs));
            admIDTxt.setText(String.valueOf(currentAdminID));
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(ManagePet.this, ex);
        }
    }
    
    public void closeDB()
    {
        try
        {
            rs.close();
            st.close();
            con.close();
        }
        
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(ManagePet.this, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        petIDTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        typeTxt = new javax.swing.JTextField();
        speciesTxt = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        petTable = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        priceTxt = new javax.swing.JTextField();
        ageTxt = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        admIDTxt = new javax.swing.JTextField();
        imageButton = new javax.swing.JButton();
        imageLable = new javax.swing.JLabel();
        imageLable2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Pet");
        setMaximumSize(new java.awt.Dimension(900, 550));
        setMinimumSize(new java.awt.Dimension(900, 550));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 27)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(193, 193, 255));
        jLabel20.setText("PET LIST");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(143, 144, 150));
        jLabel21.setText("Name");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(143, 144, 150));
        jLabel22.setText("Pet ID");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(143, 144, 150));
        jLabel23.setText("Type");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(143, 144, 150));
        jLabel24.setText("Species");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(143, 144, 150));
        jLabel25.setText("Price");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(143, 144, 150));
        jLabel26.setText("Age");

        petIDTxt.setEditable(false);
        petIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petIDTxtActionPerformed(evt);
            }
        });

        typeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeTxtActionPerformed(evt);
            }
        });

        petTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Pet_ID", "Name", "Type", "Species", "Age", "Price"
            }
        ));
        petTable.setRowHeight(20);
        petTable.setSelectionBackground(new java.awt.Color(204, 204, 255));
        petTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                petTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(petTable);

        addButton.setBackground(new java.awt.Color(78, 95, 200));
        addButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setBackground(new java.awt.Color(78, 95, 200));
        removeButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        removeButton.setForeground(new java.awt.Color(255, 255, 255));
        removeButton.setText("REMOVE");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(78, 95, 200));
        editButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setText("EDIT");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(78, 95, 200));
        clearButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(78, 95, 200));
        jLabel27.setText("Manage Pet");

        backLabel.setForeground(new java.awt.Color(144, 143, 150));
        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petscare/Icon/back (1) (1) (1) (1).png"))); // NOI18N
        backLabel.setText(" BACK");
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(144, 143, 150));
        jLabel16.setText("Admin ID");

        admIDTxt.setEditable(false);
        admIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admIDTxtActionPerformed(evt);
            }
        });

        imageButton.setBackground(new java.awt.Color(78, 95, 200));
        imageButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        imageButton.setForeground(new java.awt.Color(255, 255, 255));
        imageButton.setText("Browse Image");
        imageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageButtonActionPerformed(evt);
            }
        });

        imageLable.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        imageLable.setForeground(new java.awt.Color(144, 143, 150));
        imageLable.setText("Image");

        imageLable2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        imageLable2.setForeground(new java.awt.Color(144, 143, 150));
        imageLable2.setText(" No Image Chose");
        imageLable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(backLabel)
                        .addGap(299, 299, 299)
                        .addComponent(jLabel27)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22)
                                .addComponent(jLabel23))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(petIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nameTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(imageLable2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(imageLable)
                            .addGap(18, 18, 18)
                            .addComponent(imageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(18, 18, 18)
                            .addComponent(admIDTxt))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel25)
                                .addComponent(jLabel26)
                                .addComponent(jLabel24))
                            .addGap(34, 34, 34)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(speciesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(removeButton)
                        .addGap(41, 41, 41)
                        .addComponent(clearButton)))
                .addGap(131, 131, 131))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(jLabel20)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel27))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backLabel)))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(speciesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(petIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(typeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(admIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imageButton)
                            .addComponent(imageLable))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imageLable2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(removeButton)
                    .addComponent(clearButton)
                    .addComponent(editButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(914, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void petIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petIDTxtActionPerformed

    private void typeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeTxtActionPerformed

    private void petTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petTableMouseClicked
        // TODO add your handling code here:

        try
        {
            int selectRow = petTable.getSelectedRow();
            int SelectID = Integer.parseInt(petTable.getModel().getValueAt(selectRow,0).toString());

            String query = "SELECT * FROM Pet WHERE PetID = " + SelectID;
            rs = st.executeQuery(query);

            rs.next();
            petIDTxt.setText(String.format("%d", rs.getInt("PetID")));
            nameTxt.setText(rs.getString("Pet_Name"));
            typeTxt.setText(rs.getString("Pet_Type"));
            speciesTxt.setText(rs.getString("Species"));
            priceTxt.setText(String.format("%.2f", rs.getDouble("Price")));
            ageTxt.setText(rs.getString("Age"));
            admIDTxt.setText(String.format("%d", currentAdminID));
            
            String path = rs.getString("ImagePath");
            ImageIcon image = new ImageIcon(getClass().getResource("Icon/" + path));
            Image img = image.getImage();
            Image imgImage = img.getScaledInstance(imageLable2.getWidth(),imageLable2.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(imgImage);
            imageLable2.setIcon(scaledIcon);
            imageLable2.setText(rs.getString("ImagePath"));
        }

        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(ManagePet.this, ex);
        }
    }//GEN-LAST:event_petTableMouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        if(ageTxt.getText().isEmpty() || speciesTxt.getText().isEmpty() || nameTxt.getText().isEmpty() || priceTxt.getText().isEmpty() || typeTxt.getText().isEmpty() || imageLable2.getIcon() == null)
            JOptionPane.showMessageDialog(this, "Missing Information", "Error", JOptionPane.WARNING_MESSAGE);
        else
        {
            try
            {
                if(Integer.parseInt(priceTxt.getText()) <= 0)
                {
                    JOptionPane.showMessageDialog(this, "Enter Positive Value", "Price Error", JOptionPane.WARNING_MESSAGE);
                }
                else
                {
                    PreparedStatement insertQuery = con.prepareStatement("INSERT INTO Pet (Age, Species, Pet_Name, Price, AdminID, Pet_Type, ImagePath)\n" +
                        "VALUES (?, ?, ?, ?, ?, ?, ?)");

                    insertQuery.setString(1, ageTxt.getText());
                    insertQuery.setString(2, speciesTxt.getText());
                    insertQuery.setString(3, nameTxt.getText());
                    insertQuery.setDouble(4, Double.valueOf(priceTxt.getText()));
                    insertQuery.setInt(5, Integer.valueOf(admIDTxt.getText()));
                    insertQuery.setString(6, typeTxt.getText());
                    insertQuery.setString(7, imageLable2.getText());

                    int result = insertQuery.executeUpdate();
                    if(result == 1)
                    JOptionPane.showMessageDialog(ManagePet.this, "Pet: " + nameTxt.getText()  + " is Addedd");

                    closeDB();
                    fillTable();
                }
            }

            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
            }
            
            catch (NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(this, "You Enter Wrong Entery Type", "Error", JOptionPane.WARNING_MESSAGE);
            }

            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(ManagePet.this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:

        try
        {
            int confirm = JOptionPane.showConfirmDialog(ManagePet.this, "You Want to Delete Selected Recored?", "Delete Recored", JOptionPane.YES_NO_OPTION);
            if(confirm == JOptionPane.YES_OPTION)
            {
                String DeleteQuery = "DELETE FROM Pet WHERE PetID = " + petIDTxt.getText();
                int result = st.executeUpdate(DeleteQuery);
                if(result == 1)
                JOptionPane.showMessageDialog(ManagePet.this, "Selected Recored is Deleted");

                petIDTxt.setText("");
                nameTxt.setText("");
                typeTxt.setText("");
                speciesTxt.setText("");
                priceTxt.setText("");
                ageTxt.setText("");
                imageLable2.setIcon(null);
                imageLable2.setText(" No Image Chose");
                admIDTxt.setText(String.valueOf(currentAdminID));

                closeDB();
                fillTable();
            }
        }

        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(ManagePet.this, ex.getMessage());
        }

        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(ManagePet.this, ex.getMessage());
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        if(ageTxt.getText().isEmpty() || speciesTxt.getText().isEmpty() || nameTxt.getText().isEmpty() || priceTxt.getText().isEmpty() || typeTxt.getText().isEmpty() || imageLable2.getIcon() == null)
            JOptionPane.showMessageDialog(this, "Missing Information", "Error", JOptionPane.WARNING_MESSAGE);
        else
        {
            try
            {
                if(Integer.parseInt(priceTxt.getText()) <= 0)
                {
                    JOptionPane.showMessageDialog(this, "Enter Positive Value", "Price Error", JOptionPane.WARNING_MESSAGE);
                }
                else
                {
                    PreparedStatement updateQuery = con.prepareStatement("UPDATE Pet SET Pet_Name = ?, Age = ?, Species = ?, Price = ?, Pet_Type = ?, ImagePath = ? ,AdminID = ? WHERE PetID = ?");

                    updateQuery.setString(1, nameTxt.getText());
                    updateQuery.setString(2, ageTxt.getText());
                    updateQuery.setString(3, speciesTxt.getText());
                    updateQuery.setDouble(4, Double.valueOf(priceTxt.getText()));
                    updateQuery.setString(5, typeTxt.getText());
                    updateQuery.setString(6, imageLable2.getText());
                    updateQuery.setInt(7, Integer.valueOf(admIDTxt.getText()));
                    updateQuery.setInt(8, Integer.valueOf(petIDTxt.getText()));

                    int result = updateQuery.executeUpdate();
                    if(result == 1)
                    JOptionPane.showMessageDialog(ManagePet.this, "Selected Recored is Updated");
                    else
                    JOptionPane.showMessageDialog(ManagePet.this, "Failed: Selected Recored is not Updated");

                    closeDB();
                    fillTable();
                }
            }

            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(ManagePet.this, ex.getMessage());
            }
            
            catch (NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(this, "You Enter Wrong Entery Type", "Error", JOptionPane.WARNING_MESSAGE);
            }

            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(ManagePet.this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:

        petIDTxt.setText("");
        nameTxt.setText("");
        typeTxt.setText("");
        speciesTxt.setText("");
        priceTxt.setText("");
        ageTxt.setText("");
        imageLable2.setIcon(null);
        imageLable2.setText(" No Image Chose");
        admIDTxt.setText(String.valueOf(currentAdminID));
    }//GEN-LAST:event_clearButtonActionPerformed

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // TODO add your handling code here:

        this.setVisible(false);
        Admin admin = new Admin();
        admin.setVisible(true);
    }//GEN-LAST:event_backLabelMouseClicked

    private void admIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admIDTxtActionPerformed

    private void imageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser imageChooser = new JFileChooser("C:\\Users\\Mzts5\\Downloads\\PetsCare\\src\\petscare\\Icon");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image files (*.PNG,*.JPG, *.JPEG)", "PNG","JPG", "JPEG");
        imageChooser.setFileFilter(filter);

        int result = imageChooser.showOpenDialog(this);

        if(result == JFileChooser.APPROVE_OPTION)
        {
            File imageFile = imageChooser.getSelectedFile();
            selectedImagePath = imageFile.getName();

            ImageIcon image = new ImageIcon(getClass().getResource("Icon/" + selectedImagePath));
            Image img = image.getImage();
            Image imgImage = img.getScaledInstance(imageLable2.getWidth(),imageLable2.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(imgImage);
            imageLable2.setIcon(scaledIcon);
            imageLable2.setText(selectedImagePath);
        }
    }//GEN-LAST:event_imageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagePet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagePet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagePet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagePet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagePet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField admIDTxt;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JLabel backLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton imageButton;
    private javax.swing.JLabel imageLable;
    private javax.swing.JLabel imageLable2;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField petIDTxt;
    private javax.swing.JTable petTable;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JButton removeButton;
    private javax.swing.JTextField speciesTxt;
    private javax.swing.JTextField typeTxt;
    // End of variables declaration//GEN-END:variables
}
