/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petscare;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.util.InputMismatchException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils; 
import static petscare.Admin.currentAdminID;

/**
 *
 * @author Maryam Tariq
 */
public class ManageEmp extends javax.swing.JFrame {
    
    Connection con;
    Statement st;
    ResultSet rs;

    /**
     * Creates new form ManageEmp
     */
    public ManageEmp() {
        initComponents();
        fillTable();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        addWindowListener(
            new WindowAdapter()
            {
                @Override
                public void windowClosed(WindowEvent event)
                {
                    closeDB();
                    System.exit(0);
                }
            }
        );
    }
    
    public void fillTable()
    {
        try
        {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/PetsCare","root","root");
            st=con.createStatement();
            rs=st.executeQuery("SELECT * FROM Employee");
            
            Emp_Table.setModel(DbUtils.resultSetToTableModel(rs));
            admIDTxt.setText(String.valueOf(currentAdminID));
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(ManageEmp.this, ex);
        }
    }
    
    public void closeDB()
    {
        try
        {
            rs.close();
            st.close();
            con.close();
        }
        
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(ManageEmp.this, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        EmpIDtxt = new javax.swing.JTextField();
        fNameTxt = new javax.swing.JTextField();
        lNameTxt = new javax.swing.JTextField();
        userNameTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Emp_Table = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        passTxt = new javax.swing.JTextField();
        phoneTxt = new javax.swing.JTextField();
        hourTxt = new javax.swing.JTextField();
        salaryTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        genderBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        ageTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        admIDTxt = new javax.swing.JTextField();
        backLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Employee");
        setMaximumSize(new java.awt.Dimension(900, 550));
        setMinimumSize(new java.awt.Dimension(900, 550));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(78, 95, 200));
        jLabel4.setText("Manage Employee");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(144, 143, 150));
        jLabel5.setText("First Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(144, 143, 150));
        jLabel6.setText("Empoyee ID");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(144, 143, 150));
        jLabel7.setText("Last Name");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(144, 143, 150));
        jLabel8.setText("Gender");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(144, 143, 150));
        jLabel9.setText("Salary");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(144, 143, 150));
        jLabel10.setText("Phone");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(144, 143, 150));
        jLabel11.setText("Password");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(144, 143, 150));
        jLabel12.setText("User Name");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(144, 143, 150));
        jLabel13.setText("WorkingHours");

        EmpIDtxt.setEditable(false);
        EmpIDtxt.setColumns(15);
        EmpIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpIDtxtActionPerformed(evt);
            }
        });

        fNameTxt.setColumns(15);

        lNameTxt.setColumns(15);
        lNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameTxtActionPerformed(evt);
            }
        });

        Emp_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee_ID", "FirstName", "LastName", "Phone", "Age", "UserName", "Password", "WorkingHours", "Salary", "Gender"
            }
        ));
        Emp_Table.setRowHeight(20);
        Emp_Table.setSelectionBackground(new java.awt.Color(204, 204, 255));
        Emp_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Emp_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Emp_Table);

        addButton.setBackground(new java.awt.Color(78, 95, 200));
        addButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setBackground(new java.awt.Color(78, 95, 200));
        removeButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        removeButton.setForeground(new java.awt.Color(255, 255, 255));
        removeButton.setText("REMOVE");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(78, 95, 200));
        editButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setText("EDIT");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(78, 95, 200));
        clearButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        phoneTxt.setText("05");
        phoneTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTxtActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 27)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(193, 193, 255));
        jLabel15.setText("EMPLOYEE LIST");

        genderBox.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        genderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        genderBox.setSelectedIndex(-1);
        genderBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderBoxActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(144, 143, 150));
        jLabel14.setText("Age");

        ageTxt.setColumns(15);
        ageTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTxtActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(144, 143, 150));
        jLabel16.setText("Admin ID");

        admIDTxt.setEditable(false);
        admIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admIDTxtActionPerformed(evt);
            }
        });

        backLabel.setForeground(new java.awt.Color(144, 143, 150));
        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petscare/Icon/back (1) (1) (1) (1).png"))); // NOI18N
        backLabel.setText(" BACK");
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel8))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(genderBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ageTxt)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EmpIDtxt)
                                    .addComponent(fNameTxt)
                                    .addComponent(lNameTxt)))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hourTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(admIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(removeButton)
                        .addGap(32, 32, 32)
                        .addComponent(clearButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(302, 302, 302))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(backLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backLabel)
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(EmpIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(fNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(passTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(hourTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(salaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(removeButton)
                    .addComponent(clearButton)
                    .addComponent(editButton)
                    .addComponent(jLabel16)
                    .addComponent(admIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(914, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EmpIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpIDtxtActionPerformed

    private void lNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameTxtActionPerformed

    private void Emp_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Emp_TableMouseClicked
        // TODO add your handling code here:

        try
        {
            int selectRow = Emp_Table.getSelectedRow();
            int SelectID = Integer.parseInt(Emp_Table.getModel().getValueAt(selectRow,0).toString());

            String query = "SELECT * FROM Employee WHERE EmployeeID = " + SelectID;
            rs = st.executeQuery(query);

            rs.next();
            EmpIDtxt.setText(String.format("%d", rs.getInt("EmployeeID")));
            fNameTxt.setText(rs.getString("FirstName"));
            lNameTxt.setText(rs.getString("LastName"));
            ageTxt.setText(String.format("%d", rs.getInt("Age")));
            String s = rs.getString("Gender");
            char gender = s.charAt(0);
            if(gender == 'M')
                genderBox.setSelectedIndex(0);
            else
                genderBox.setSelectedIndex(1);
            userNameTxt.setText(rs.getString("UserName"));
            passTxt.setText(rs.getString("Password"));
            phoneTxt.setText(String.format("%d", rs.getInt("Phone")));
            hourTxt.setText(String.format("%d", rs.getInt("WorkingHours")));
            salaryTxt.setText(String.format("%d", rs.getInt("Salary")));
            admIDTxt.setText(String.format("%d", currentAdminID));
        }

        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(ManageEmp.this, ex);
        }

    }//GEN-LAST:event_Emp_TableMouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        if(phoneTxt.getText().isEmpty() || genderBox.getSelectedIndex() == -1 || ageTxt.getText().isEmpty() || userNameTxt.getText().isEmpty() || passTxt.getText().isEmpty() || fNameTxt.getText().isEmpty() || lNameTxt.getText().isEmpty() || salaryTxt.getText().isEmpty() || hourTxt.getText().isEmpty())
            JOptionPane.showMessageDialog(ManageEmp.this, "Missing Information", "Error", JOptionPane.WARNING_MESSAGE);
        
        else if (!phoneTxt.getText().matches("(05)([0-9]{8})"))
                JOptionPane.showMessageDialog(ManageEmp.this, "Invalid Phone Number: Please Enter 10 digit Start with 05 only", "Invalid Phone Number", JOptionPane.ERROR_MESSAGE);
        else if(Integer.parseInt(ageTxt.getText()) <=0 || Double.parseDouble(salaryTxt.getText()) <=0 || Integer.parseInt(hourTxt.getText()) <=0)
            JOptionPane.showMessageDialog(ManageEmp.this, "Please Enter Positive Number", "Enter Negivite Number", JOptionPane.ERROR_MESSAGE);
        else
        {
            try
            {
                PreparedStatement insertQuery = con.prepareStatement("INSERT INTO Employee (Phone, Gender, Age, UserName, Password, FirstName, LastName, Salary, WorkingHours, AdminID)\n" +
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");

                insertQuery.setInt(1, Integer.valueOf(phoneTxt.getText()));
                insertQuery.setString(2, (genderBox.getSelectedIndex() == 0) ? "M" : "F");
                insertQuery.setInt(3, Integer.valueOf(ageTxt.getText()));
                insertQuery.setString(4, userNameTxt.getText());
                insertQuery.setString(5, passTxt.getText());
                insertQuery.setString(6, fNameTxt.getText());
                insertQuery.setString(7, lNameTxt.getText());
                insertQuery.setInt(8, Integer.valueOf(salaryTxt.getText()));
                insertQuery.setInt(9, Integer.valueOf(hourTxt.getText()));
                insertQuery.setInt(10, Integer.valueOf(admIDTxt.getText()));

                int result = insertQuery.executeUpdate();
                if(result == 1)
                JOptionPane.showMessageDialog(ManageEmp.this, "Employee " + fNameTxt.getText() + " " + lNameTxt.getText() + " is Addedd");

                closeDB();
                fillTable();
            }

            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(ManageEmp.this, ex.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
            }

            catch (NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(ManageEmp.this, "You Enter Wrong Entery Type", "Error", JOptionPane.WARNING_MESSAGE);
            }

            catch(Exception ex)
            {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(ManageEmp.this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            int confirm = JOptionPane.showConfirmDialog(ManageEmp.this, "You Want to Delete Selected Recored?", "Delete Recored", JOptionPane.YES_NO_OPTION);
            if(confirm == JOptionPane.YES_OPTION)
            {
                String DeleteQuery = "DELETE FROM Employee WHERE EmployeeID = " + EmpIDtxt.getText();
                int result = st.executeUpdate(DeleteQuery);
                if(result == 1)
                JOptionPane.showMessageDialog(ManageEmp.this, "Selected Recored is Deleted");

                EmpIDtxt.setText("");
                fNameTxt.setText("");
                lNameTxt.setText("");
                ageTxt.setText("");
                genderBox.setSelectedIndex(-1);
                userNameTxt.setText("");
                passTxt.setText("");
                phoneTxt.setText("05");
                hourTxt.setText("");
                salaryTxt.setText("");
                admIDTxt.setText(String.valueOf(currentAdminID));

                closeDB();
                fillTable();
            }
        }

        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(ManageEmp.this, ex.getMessage());
        }

        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(ManageEmp.this, ex.getMessage());
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        if(phoneTxt.getText().isEmpty() || genderBox.getSelectedIndex() == -1 || ageTxt.getText().isEmpty() || userNameTxt.getText().isEmpty() || passTxt.getText().isEmpty() || fNameTxt.getText().isEmpty() || lNameTxt.getText().isEmpty() || salaryTxt.getText().isEmpty() || hourTxt.getText().isEmpty())
            JOptionPane.showMessageDialog(ManageEmp.this, "Missing Information", "Error", JOptionPane.WARNING_MESSAGE);
        
        else if (!phoneTxt.getText().matches("(05)([0-9]{8})"))
                JOptionPane.showMessageDialog(ManageEmp.this, "Invalid Phone Number: Please Enter 10 digit Start with 05 only", "Invalid Phone Number", JOptionPane.ERROR_MESSAGE);
        
        else if(Integer.parseInt(ageTxt.getText()) <=0 || Double.parseDouble(salaryTxt.getText()) <=0 || Integer.parseInt(hourTxt.getText()) <=0)
            JOptionPane.showMessageDialog(ManageEmp.this, "Please Enter Positive Number", "Enter Negivite Number", JOptionPane.ERROR_MESSAGE);
        
        else
        {
            try
            {
                PreparedStatement updateQuery = con.prepareStatement("UPDATE EMPLOYEE SET Phone = ?, Gender = ?, Age = ?, UserName = ?, Password = ?, FirstName = ?, LastName = ?, Salary = ?, WorkingHours = ?, AdminID = ? WHERE EmployeeID = ?");

                updateQuery.setInt(1, Integer.valueOf(phoneTxt.getText()));
                updateQuery.setString(2, genderBox.getSelectedIndex() == 0 ? "M" : "F");
                updateQuery.setInt(3, Integer.valueOf(ageTxt.getText()));
                updateQuery.setString(4, userNameTxt.getText());
                updateQuery.setString(5, passTxt.getText());
                updateQuery.setString(6, fNameTxt.getText());
                updateQuery.setString(7, lNameTxt.getText());
                updateQuery.setInt(8, Integer.valueOf(salaryTxt.getText()));
                updateQuery.setInt(9, Integer.valueOf(hourTxt.getText()));
                updateQuery.setInt(10, Integer.valueOf(admIDTxt.getText()));
                updateQuery.setInt(11, Integer.valueOf(EmpIDtxt.getText()));

                int result = updateQuery.executeUpdate();
                if(result == 1)
                JOptionPane.showMessageDialog(ManageEmp.this, "Selected Recored is Updated");
                else
                JOptionPane.showMessageDialog(ManageEmp.this, "Failed: Selected Recored is not Updated");

                closeDB();
                fillTable();
            }

            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(ManageEmp.this, ex.getMessage());
            }

            catch (NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(ManageEmp.this, "You Enter Wrong entery type", "Error", JOptionPane.WARNING_MESSAGE);
            }

            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(ManageEmp.this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:

        EmpIDtxt.setText("");
        fNameTxt.setText("");
        lNameTxt.setText("");
        ageTxt.setText("");
        genderBox.setSelectedIndex(-1);
        userNameTxt.setText("");
        passTxt.setText("");
        phoneTxt.setText("05");
        hourTxt.setText("");
        salaryTxt.setText("");
        admIDTxt.setText(String.valueOf(currentAdminID));
    }//GEN-LAST:event_clearButtonActionPerformed

    private void phoneTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTxtActionPerformed

    private void genderBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderBoxActionPerformed

    private void ageTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTxtActionPerformed

    private void admIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admIDTxtActionPerformed

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // TODO add your handling code here:

        this.setVisible(false);
        Admin admin = new Admin();
        admin.setVisible(true);
    }//GEN-LAST:event_backLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmpIDtxt;
    private javax.swing.JTable Emp_Table;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField admIDTxt;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JLabel backLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField fNameTxt;
    private javax.swing.JComboBox<String> genderBox;
    private javax.swing.JTextField hourTxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lNameTxt;
    private javax.swing.JTextField passTxt;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JButton removeButton;
    private javax.swing.JTextField salaryTxt;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
